import type { ToolDefinition } from './types';
import { generateSlugsForId, defaultFaqs } from './types';

export const compressTools: ToolDefinition[] = [
  {
    id: 'compress-pdf',
    category: 'compress',
    iconName: 'Minimize2',
    slugs: generateSlugsForId('compress-pdf', {
      en: 'compress-pdf',
      id: 'kompres-pdf',
      es: 'comprimir-pdf',
      fr: 'compresser-pdf',
      de: 'pdf-komprimieren',
      ja: 'pdf-asshuku',
      pt: 'comprimir-pdf',
      ru: 'szhat-pdf',
      zh: 'yasuo-pdf',
      ar: 'daght-pdf',
      hi: 'pdf-compress-kare',
      it: 'comprimi-pdf',
      ko: 'pdf-apchuk',
      nl: 'pdf-comprimeren',
      tr: 'pdf-sikistir',
      pl: 'kompresuj-pdf',
      vi: 'nen-pdf',
      th: 'bip-at-pdf',
      sv: 'komprimera-pdf',
      cs: 'komprimovat-pdf',
      da: 'komprimer-pdf',
      el: 'sympiesi-pdf',
      fi: 'pakkaa-pdf',
      he: 'dchisat-pdf',
      hu: 'pdf-tomorites',
      no: 'komprimer-pdf',
      ro: 'comprimare-pdf',
      sk: 'komprimovat-pdf',
      uk: 'stysnuty-pdf',
      ms: 'kompres-pdf-online',
    }),
    seo: {
      en: {
        title: 'Compress PDF Online - Reduce File Size by 60-90% Locally',
        h1: 'Compress PDF Documents without Losing Quality',
        description: 'Shrink large PDF files up to 90% using adaptive lossless and DPI rasterization techniques directly in WebAssembly.',
        faqs: defaultFaqs('Compress PDF', 'en'),
      },
      id: {
        title: 'Kompres PDF Online Gratis - Kecilkan Ukuran File Hingga 90%',
        h1: 'Kecilkan Ukuran Berkas PDF Tanpa Mengurangi Kualitas',
        description: 'Kompres file PDF berukuran megabita menjadi sangat ringan untuk dikirim lewat email atau WhatsApp dengan pemrosesan lokal.',
        faqs: defaultFaqs('Kompres PDF', 'id'),
      },
      es: {
        title: 'Comprimir PDF Online - Reducir Tamaño de Archivo sin Subidas',
        h1: 'Comprime Archivos PDF manteniendo una Excelente Calidad',
        description: 'Reduce el peso de tus documentos PDF grandes hasta un 90% mediante técnicas avanzadas en la memoria de tu navegador.',
        faqs: defaultFaqs('Comprimir PDF', 'es'),
      },
    },
  },
  {
    id: 'compress-pdf-for-email',
    category: 'compress',
    iconName: 'Minimize2',
    slugs: generateSlugsForId('compress-pdf-for-email', {
      en: 'compress-pdf-for-email',
      id: 'kompres-pdf-untuk-email',
      es: 'comprimir-pdf-para-correo',
      fr: 'compresser-pdf-pour-email',
      de: 'pdf-komprimieren-fuer-email',
      ja: 'email-yow-pdf-asshuku',
      pt: 'comprimir-pdf-para-email',
      ru: 'szhat-pdf-dlya-email',
      zh: 'youjian-yasuo-pdf',
      ar: 'daght-pdf-lil-barid',
      hi: 'email-ke-liye-pdf-compress',
      it: 'comprimi-pdf-per-email',
      ko: 'email-yong-pdf-apchuk',
      nl: 'pdf-comprimeren-voor-email',
      tr: 'eposta-icin-pdf-sikistir',
      pl: 'kompresuj-pdf-do-emaila',
      vi: 'nen-pdf-cho-email',
      th: 'bip-at-pdf-samrap-email',
      sv: 'komprimera-pdf-for-epost',
      cs: 'komprimovat-pdf-pro-email',
      da: 'komprimer-pdf-til-e-mail',
      el: 'sympiesi-pdf-gia-email',
      fi: 'pakkaa-pdf-sahkopostia-varten',
      he: 'dchisat-pdf-ledoar-alektroni',
      hu: 'pdf-tomorites-emailhez',
      no: 'komprimer-pdf-for-epost',
      ro: 'comprimare-pdf-pentru-email',
      sk: 'komprimovat-pdf-pre-email',
      uk: 'stysnuty-pdf-dlya-email',
      ms: 'kompres-pdf-untuk-email',
    }),
    seo: {
      en: {
        title: 'Compress PDF for Email',
        h1: 'Compress PDF Files for Email Attachments (100% Free & Private)',
        description: 'Bypass Gmail, Outlook, and Yahoo file attachment size limits. Compress large PDFs under 25MB locally inside browser memory with 0 bytes upload.',
        faqs: defaultFaqs('Compress PDF for Email', 'en'),
      },
      id: {
        title: 'Kompres PDF untuk Email',
        h1: 'Kompres Berkas PDF untuk Lampiran Email (Aman & Tanpa Upload)',
        description: 'Atasi batas lampiran Gmail dan Outlook (25MB). Kecilkan ukuran PDF secara instan di memori browser tanpa mengunggah dokumen pribadi ke server.',
        faqs: defaultFaqs('Kompres PDF untuk Email', 'id'),
      },
      es: {
        title: 'Comprimir PDF para Correo',
        h1: 'Comprime Archivos PDF para Enviar por Correo Electrónico sin Límites',
        description: 'Supera los límites de archivos adjuntos de Gmail and Outlook. Comprime archivos PDF grandes localmente en la memoria del navegador.',
        faqs: defaultFaqs('Comprimir PDF para Correo', 'es'),
      },
    },
  },
  {
    id: 'compress-pdf-to-100kb',
    category: 'compress',
    iconName: 'Minimize2',
    slugs: generateSlugsForId('compress-pdf-to-100kb', {
      en: 'compress-pdf-to-100kb',
      id: 'kompres-pdf-100kb',
      es: 'comprimir-pdf-a-100kb',
      fr: 'compresser-pdf-a-100ko',
      de: 'pdf-auf-100kb-komprimieren',
      ja: 'pdf-wo-100kb-ni-asshuku',
      pt: 'comprimir-pdf-para-100kb',
      ru: 'szhat-pdf-do-100kb',
      zh: 'yasuo-pdf-dao-100kb',
      ar: 'daght-pdf-ila-100kb',
      hi: 'pdf-ko-100kb-tak-compress-kare',
      it: 'comprimi-pdf-a-100kb',
      ko: 'pdf-reul-100kb-ro-apchuk',
      nl: 'pdf-comprimeren-tot-100kb',
      tr: 'pdf-yi-100kbya-sikistir',
      pl: 'kompresuj-pdf-do-100kb',
      vi: 'nen-pdf-xuong-100kb',
      th: 'bipat-pdf-pen-100kb',
      sv: 'komprimera-pdf-till-100kb',
      cs: 'komprimovat-pdf-na-100kb',
      da: 'komprimer-pdf-til-100kb',
      el: 'sympiesi-pdf-se-100kb',
      fi: 'pakkaa-pdf-100kb-kokoon',
      he: 'dchisat-pdf-le-100kb',
      hu: 'pdf-tomorites-100kb-ra',
      no: 'komprimer-pdf-til-100kb',
      ro: 'comprimare-pdf-la-100kb',
      sk: 'komprimovat-pdf-na-100kb',
      uk: 'stysnuty-pdf-do-100kb',
      ms: 'kompres-pdf-kepada-100kb',
    }),
    seo: {
      en: {
        title: 'Compress PDF to 100KB',
        h1: 'Compress PDF Files to 100KB Online (Free & Private)',
        description: 'Shrink your large PDF documents under 100KB for government portals, job applications, or visa forms completely in your browser.',
        faqs: defaultFaqs('Compress PDF to 100KB', 'en'),
      },
      id: {
        title: 'Kompres PDF ke 100KB',
        h1: 'Kecilkan File PDF Hingga Di Bawah 100KB Secara Instan',
        description: 'Sangat cocok untuk pendaftaran CPNS, visa, beasiswa, atau unggahan berkas portal instansi pemerintah. Kompres lokal aman.',
        faqs: defaultFaqs('Kompres PDF ke 100KB', 'id'),
      },
    },
  },
  {
    id: 'compress-pdf-without-losing-quality',
    category: 'compress',
    iconName: 'Minimize2',
    slugs: generateSlugsForId('compress-pdf-without-losing-quality', {
      en: 'compress-pdf-without-losing-quality',
      id: 'kompres-pdf-tanpa-mengurangi-kualitas',
      es: 'comprimir-pdf-sin-perder-calidad',
      fr: 'compresser-pdf-sans-perte-de-qualite',
      de: 'pdf-komprimieren-ohne-qualitaetsverlust',
      ja: 'hinshitsu-wo-otosazu-ni-pdf-wo-asshuku',
      pt: 'comprimir-pdf-sem-perder-qualidade',
      ru: 'szhat-pdf-bez-poteri-kachestva',
      zh: 'wusun-yasuo-pdf',
      ar: 'daght-pdf-bidun-fuqdan-aljawda',
      hi: 'quality-khoye-bina-pdf-compress-kare',
      it: 'comprimi-pdf-senza-perdere-qualita',
      ko: 'pumjil-sonsil-eopsi-pdf-apchuk',
      nl: 'pdf-comprimeren-zonder-kwaliteitsverlies',
      tr: 'kalite-kaybetmeden-pdf-sikistir',
      pl: 'kompresuj-pdf-bez-utraty-jakosci',
      vi: 'nen-pdf-khong-giam-chat-luong',
      th: 'bipat-pdf-doi-mai-sia-khunnaphap',
      sv: 'komprimera-pdf-utan-att-forlora-kvalitet',
      cs: 'komprimovat-pdf-bez-ztraty-kvality',
      da: 'komprimer-pdf-uden-kvalitetstab',
      el: 'sympiesi-pdf-xoris-apoleia-poiotitas',
      fi: 'pakkaa-pdf-ilman-laadun-heikkenemista',
      he: 'dchisat-pdf-lelo-ovdan-eichut',
      hu: 'pdf-tomorites-minosegromlas-nelkul',
      no: 'komprimer-pdf-uten-kvalitetstap',
      ro: 'comprimare-pdf-fara-pierderea-calitatii',
      sk: 'komprimovat-pdf-bez-straty-kvality',
      uk: 'stysnuty-pdf-bez-vtraty-yakosti',
      ms: 'kompres-pdf-tanpa-hilang-kualiti',
    }),
    seo: {
      en: {
        title: 'Compress PDF Without Losing Quality',
        h1: 'Compress PDF Documents Online Without Losing Quality',
        description: 'Reduce PDF file size while keeping high-resolution vectors and texts perfectly sharp. 100% private client-side processing.',
        faqs: defaultFaqs('Compress PDF Without Losing Quality', 'en'),
      },
      id: {
        title: 'Kompres PDF Tanpa Mengurangi Kualitas',
        h1: 'Kecilkan PDF Online Tanpa Merusak Ketajaman Teks & Gambar',
        description: 'Pertahankan kegunaan profesional dengan kompresi tingkat tinggi yang tetap menjaga kejelasan teks, diagram, dan gambar.',
        faqs: defaultFaqs('Kompres PDF Tanpa Mengurangi Kualitas', 'id'),
      },
    },
  },
  {
    id: 'reduce-pdf-size-offline',
    category: 'compress',
    iconName: 'Minimize2',
    slugs: generateSlugsForId('reduce-pdf-size-offline', {
      en: 'reduce-pdf-size-offline',
      id: 'kurangi-ukuran-pdf-secara-offline',
      es: 'reducir-el-tama-o-del-pdf-sin-conexi-n',
      fr: 'r-duire-la-taille-du-pdf-hors-ligne',
      de: 'pdf-gr-e-offline-reduzieren',
      ja: 'reduce-pdf-size-offline',
      pt: 'reduzir-o-tamanho-do-pdf-off-line',
      ru: 'reduce-pdf-size-offline',
      zh: 'reduce-pdf-size-offline',
      ar: 'reduce-pdf-size-offline',
      it: 'riduci-le-dimensioni-del-pdf-offline',
      ko: 'reduce-pdf-size-offline',
      nl: 'verklein-de-pdf-grootte-offline',
      tr: 'evrimd-pdf-boyutunu-k-lt',
      pl: 'zmniejsz-rozmiar-pliku-pdf-w-trybie-offline',
      vi: 'gi-m-k-ch-th-c-pdf-ngo-i-tuy-n',
      th: 'reduce-pdf-size-offline',
      sv: 'minska-pdf-storlek-offline',
      cs: 'zmen-it-velikost-pdf-offline',
      da: 'reducere-pdf-st-rrelse-offline',
      el: 'reduce-pdf-size-offline',
      fi: 'pienenn-pdf-kokoa-offline-tilassa',
      he: 'reduce-pdf-size-offline',
      hu: 'a-pdf-m-ret-nek-cs-kkent-se-offline-m-dban',
      no: 'redusere-pdf-st-rrelse-offline',
      ro: 'reduce-i-dimensiunea-pdf-offline',
      sk: 'zmen-i-ve-kos-pdf-offline',
      uk: 'reduce-pdf-size-offline',
      ms: 'mengurangkan-saiz-pdf-di-luar-talian',
    }),
    seo: {
      en: {
        title: 'Reduce PDF Size Offline',
        h1: 'Reduce PDF Size Completely Offline in Your Browser',
        description: 'Reduce the size of your PDF documents offline directly in your browser without any server uploads. 100% secure.',
        faqs: defaultFaqs('Reduce PDF Size Offline', 'en'),
      },
      id: {
        title: 'Kurangi Ukuran PDF Offline',
        h1: 'Kurangi Ukuran File PDF Secara Offline',
        description: 'Kompres dokumen PDF Anda secara lokal langsung di memori browser Anda, tanpa internet, tanpa unggahan ke server.',
        faqs: defaultFaqs('Kurangi Ukuran PDF Offline', 'id'),
      },
    },
  },
];
