import type { ToolDefinition } from './types';
import { generateSlugsForId, defaultFaqs } from './types';

export const compressTools: ToolDefinition[] = [
  {
    id: 'compress-pdf',
    category: 'compress',
    iconName: 'Minimize2',
    slugs: generateSlugsForId('compress-pdf', {
      en: 'compress-pdf',
      id: 'kompres-pdf',
      es: 'comprimir-pdf',
      fr: 'compresser-pdf',
      de: 'pdf-komprimieren',
      ja: 'pdf-asshuku',
      pt: 'comprimir-pdf',
      ru: 'szhat-pdf',
      zh: 'yasuo-pdf',
      ar: 'daght-pdf',
      hi: 'pdf-compress-kare',
      it: 'comprimi-pdf',
      ko: 'pdf-apchuk',
      nl: 'pdf-comprimeren',
      tr: 'pdf-sikistir',
      pl: 'kompresuj-pdf',
      vi: 'nen-pdf',
      th: 'bip-at-pdf',
      sv: 'komprimera-pdf',
      cs: 'komprimovat-pdf',
      da: 'komprimer-pdf',
      el: 'sympiesi-pdf',
      fi: 'pakkaa-pdf',
      he: 'dchisat-pdf',
      hu: 'pdf-tomorites',
      no: 'komprimer-pdf',
      ro: 'comprimare-pdf',
      sk: 'komprimovat-pdf',
      uk: 'stysnuty-pdf',
      ms: 'kompres-pdf-online',
    }),
    seo: {
      en: {
        title: 'Compress PDF Online - Reduce File Size by 60-90% Locally',
        h1: 'Compress PDF Documents without Losing Quality',
        description: 'Shrink large PDF files up to 90% using adaptive lossless and DPI rasterization techniques directly in WebAssembly.',
        faqs: defaultFaqs('Compress PDF', 'en'),
      },
      id: {
        title: 'Kompres PDF Online Gratis - Kecilkan Ukuran File Hingga 90%',
        h1: 'Kecilkan Ukuran Berkas PDF Tanpa Mengurangi Kualitas',
        description: 'Kompres file PDF berukuran megabita menjadi sangat ringan untuk dikirim lewat email atau WhatsApp dengan pemrosesan lokal.',
        faqs: defaultFaqs('Kompres PDF', 'id'),
      },
      es: {
        title: 'Comprimir PDF Online - Reducir Tamaño de Archivo sin Subidas',
        h1: 'Comprime Archivos PDF manteniendo una Excelente Calidad',
        description: 'Reduce el peso de tus documentos PDF grandes hasta un 90% mediante técnicas avanzadas en la memoria de tu navegador.',
        faqs: defaultFaqs('Comprimir PDF', 'es'),
      },
    },
  },
  {
    id: 'compress-pdf-for-email',
    category: 'compress',
    iconName: 'Minimize2',
    slugs: generateSlugsForId('compress-pdf-for-email', {
      en: 'compress-pdf-for-email',
      id: 'kompres-pdf-untuk-email',
      es: 'comprimir-pdf-para-correo',
      fr: 'compresser-pdf-pour-email',
      de: 'pdf-komprimieren-fuer-email',
      ja: 'email-yow-pdf-asshuku',
      pt: 'comprimir-pdf-para-email',
      ru: 'szhat-pdf-dlya-email',
      zh: 'youjian-yasuo-pdf',
      ar: 'daght-pdf-lil-barid',
      hi: 'email-ke-liye-pdf-compress',
      it: 'comprimi-pdf-per-email',
      ko: 'email-yong-pdf-apchuk',
      nl: 'pdf-comprimeren-voor-email',
      tr: 'eposta-icin-pdf-sikistir',
      pl: 'kompresuj-pdf-do-emaila',
      vi: 'nen-pdf-cho-email',
      th: 'bip-at-pdf-samrap-email',
      sv: 'komprimera-pdf-for-epost',
      cs: 'komprimovat-pdf-pro-email',
      da: 'komprimer-pdf-til-e-mail',
      el: 'sympiesi-pdf-gia-email',
      fi: 'pakkaa-pdf-sahkopostia-varten',
      he: 'dchisat-pdf-ledoar-alektroni',
      hu: 'pdf-tomorites-emailhez',
      no: 'komprimer-pdf-for-epost',
      ro: 'comprimare-pdf-pentru-email',
      sk: 'komprimovat-pdf-pre-email',
      uk: 'stysnuty-pdf-dlya-email',
      ms: 'kompres-pdf-untuk-email',
    }),
    seo: {
      en: {
        title: 'Compress PDF for Email - Shrink Large PDF Files under 25MB',
        h1: 'Compress PDF Files for Email Attachments (100% Free & Private)',
        description: 'Bypass Gmail, Outlook, and Yahoo file attachment size limits. Compress large PDFs under 25MB locally inside browser memory with 0 bytes upload.',
        faqs: defaultFaqs('Compress PDF for Email', 'en'),
      },
      id: {
        title: 'Kompres PDF untuk Email - Kecilkan Berkas PDF Di Bawah Batas Attachment',
        h1: 'Kompres Berkas PDF untuk Lampiran Email (Aman & Tanpa Upload)',
        description: 'Atasi batas lampiran Gmail dan Outlook (25MB). Kecilkan ukuran PDF secara instan di memori browser tanpa mengunggah dokumen pribadi ke server.',
        faqs: defaultFaqs('Kompres PDF untuk Email', 'id'),
      },
      es: {
        title: 'Comprimir PDF para Correo - Reducir Tamaño para Archivos Adjuntos',
        h1: 'Comprime Archivos PDF para Enviar por Correo Electrónico sin Límites',
        description: 'Supera los límites de archivos adjuntos de Gmail y Outlook. Comprime archivos PDF grandes localmente en la memoria del navegador.',
        faqs: defaultFaqs('Comprimir PDF para Correo', 'es'),
      },
    },
  },
];
